name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # executa todo dia à meia-noite

permissions:
  contents: write  # 👈 ADICIONE ESTA LINHA!

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SayuryKato
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
